# Generated by Django 2.1.5 on 2019-01-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=3)),
                ('height', models.IntegerField(max_length=3)),
                ('body_mass_index', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Resalt',
        ),
    ]
