# Generated by Django 2.1.5 on 2019-01-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190130_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='body_mass_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='height',
            field=models.IntegerField(),
        ),
    ]
